# Basics II
## Importing Modules
So far we have explored the core Python language and used only those functions that come built in or made our own. As a general-purpose language Python doesn't aim to provide an exhaustive library of functions for all possible uses. Instead it allows you to import any additional functions you need from modules that are suited for specific applications. You probably noted earlier that instead of simply installing Python, we installed Anaconda. Anaconda is a Python distribution that additionally includes a few hundred modules that are useful for the various tasks encounterd by scientists and engineers.

There are several ways to `import` a module. The first way imports an entire module, NumPy in this example. You must `import` a module before you can use any of the functions it contains, which is usually at the beginning of the program. 

In [1]:
import numpy

This doesn't immediately make the functions in NumPy available, it just makes the module itself available. If we want to call functions from the module and use them in our program we use dot notation. For example, `numpy.ones()` calls the function `ones()` from the module `numpy`. To be a bit more efficient when using long module names we can rename them just for our program.

In [2]:
import numpy as np

Now we can call get the same function with a bit less effort using `np.ones()`.

Sometimes we only need a few functions from a module. This is achieved using the `from` keyword.

In [3]:
from numpy import ones, zeros

This imports only the `ones()` and `zeros()` functions from the module and makes them immediately callable as if they were built in without referencing the module, i.e. the dot notation is no longer needed for the functions `ones()` and `zeros()`. If we want to, we could make all functions in a module immediately callable.

In [4]:
from numpy import *

Although this is convenient, usually this is discouraged in favour of making the code more readable. It's more helpful to you or another user later on to know when you or they are using a function that's only available from a specific module.

## NumPy
As scientists and engineers NumPy is our friend. If you're already a MATLAB user, NumPy is the module in Python that gives it MATLAB-like functionality. This is mainly the ability to manipulate data contained in arrays and matrices. We start by importing the module.

In [5]:
import numpy as np

### Arrays
The central data type in NumPy is arrays. Arrays are similar to lists except that all their elements must be of the same numeric type, `float` or `int`. Manipulating arrays is typically much more efficient than lists so they will often be our preferred container for large data sets. To create an array we convert a list using the NumPy `array()` function. This function takes two arguments: the input list, and an optional type declaration. 

In [6]:
x = np.array([1,2,3,4], float)
print(x)
print(type(x))

[ 1.  2.  3.  4.]
<class 'numpy.ndarray'>


Array elements are indexed and modified using the same methods as used for lists.

In [7]:
print(x[1])

2.0


In [8]:
print(x[:2])

[ 1.  2.]


In [9]:
x[1] = 5
print(x)

[ 1.  5.  3.  4.]


We can make multidimentional arrays by converting nested lists.

In [10]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


The elements of multidimentional arrays are indexed and manipulated with comma-separated indices for each dimention.

In [11]:
print(x[1,2])

6


In [12]:
print(x[:,1])

[2 5 8]


In [13]:
x[:,1] = [9,9,9]
print(x)

[[1 9 3]
 [4 9 6]
 [7 9 9]]


There are several methods available to arrays that allow you to get more information about them. For example, we can get their shape.

In [14]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)

(2, 3)


We can find out the data type of the elements.

In [15]:
print(x.dtype)

int32


The `len()` function gives the length of the first dimention.

In [16]:
print(len(x))

2


The `size()` function gives the total numer of elements.

In [17]:
print(size(x))

6


The `in` keyword tells us if an element is present.

In [18]:
print(2 in x)

True


Arrays can be reshaped by supplying a tuple with the new dimention lengths. The `reshape()` method always creates a new array without modifying the original. Similarly, a new array with axis lengths swapped can be generated with the `transpose()` method. Or we can create a one dimentional array from a multidimetnional array with `flatten()`.

In [19]:
y = x.reshape((1,6))
print(y)

[[1 2 3 4 5 6]]


In [20]:
z = x.transpose()
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [21]:
w = x.flatten()
print(w)

[1 2 3 4 5 6]


In [22]:
print(x)

[[1 2 3]
 [4 5 6]]


Arrays can be concatenated. If we concatenate multidimentional arrays we can additionally specify the concatenation axis.

In [23]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.concatenate((x,y)))

[1 2 3 4 5 6]


In [24]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
print(np.concatenate((x,y),axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
print(np.concatenate((x,y),axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


We can also increase the dimentionality of a array by supplying a `newaxis` constant when indexing if we want to manipulate arrays in vector and matrix mathematics.

In [26]:
x = np.array([1,2,3])
print(x)
print(x.shape)

[1 2 3]
(3,)


In [27]:
y = x[:,np.newaxis]
print(y)
print(y.shape)

[[1]
 [2]
 [3]]
(3, 1)


We can manipulate arrays in other ways...

In [28]:
x = np.array([7,2,5])
print(np.sort(x))

[2 5 7]


In [29]:
print(x.clip(0,5))

[5 2 5]


In [30]:
x = np.array([1,1,1,5])
print(np.unique(x))

[1 5]


In [31]:
x = np.array([[1,2],[3,4]])
print(np.diagonal(x))

[1 4]


And finally, we can convert an array back to a list.

In [32]:
print(x.tolist())

[[1, 2], [3, 4]]


### Other ways of making arrays
Like the `range()` function to make lists, NumPy has an `arange()` function for making arrays. It has a similar `(start, stop, step)` syntax but also offers a type declaration.

In [33]:
x = np.arange(0,12,2,dtype=float)
print(x)
print(x.dtype)

[  0.   2.   4.   6.   8.  10.]
float64


There are several special types of arrays that can be automatically generated such as `ones()` and `zeros()` that take a tuple argument to specify the dimention lengths and a data type argument if needed.

In [34]:
x = ones((2,2),dtype=float)
print(x)

[[ 1.  1.]
 [ 1.  1.]]


In [35]:
x = zeros((2,4))
print(x)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


We can reuse the dimentions of an existing array to make new arrays of zeros and ones with the `zeros_like()` and `ones_like()` functions. 

In [36]:
x = np.array([[1,2,3],[4,5,6]])
y = np.zeros_like(x)
z = np.ones_like(x)
print(x)
print(y)
print(z)

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


Two functions can give us identity and identity-like arrays.

In [37]:
x = np.identity(4)
print(x)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [38]:
x = np.eye(4, k=-2)
print(x)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]]


### Array arithmatic
Mathematical operators can be used with arrays and apply element-wise by default.

In [39]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)

[5 7 9]


In [40]:
print(x-y)

[-3 -3 -3]


In [41]:
print(x*y)

[ 4 10 18]


In [42]:
print(x/y)

[ 0.25  0.4   0.5 ]


In [43]:
print(y%x) # y%x = r where q*x + r = y for integer q and r, and q > r

[0 1 0]


In [44]:
print(x**2)

[1 4 9]


In [45]:
print(x**y)

[  1  32 729]


The same element-wise operation applies for multidimentional arrays.

In [46]:
x = np.array([[1,2,3],[4,5,6]])
y = x
print(x+y)

[[ 2  4  6]
 [ 8 10 12]]


In [47]:
print(x*y)

[[ 1  4  9]
 [16 25 36]]


For mathematical operations arrays of the same dimention must have the same size.

In [48]:
x = np.array([1,2,3])
y = np.array([4,5])
print(x + y)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

But arrays of different dimentions can be *broadcast*.

In [49]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = x[0,:]
print(x + y)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


If the larger array is square, the broadcasting axis is ambiguous. `newaxis` to the rescue!

In [50]:
x = np.array([[1,2],[3,4]])
y = np.array([1,2])
print(x + y)

[[2 4]
 [4 6]]


In [51]:
z = y[:,np.newaxis]
print(x + z)

[[2 3]
 [5 6]]


Many of the most common elementary mathematical functions that are also available in NumPy and can be used on arrays element-wise: `abs`, `sign`, `sqrt`, `log`, `log10`, `exp`, `sin`, `cos`, `tan`, `arcsin`, `arccos`, `arctan`, `sinh`, `cosh`, `tanh`, `arcsinh`, `arccosh`, and `arctanh`. Other useful operators are `floor()`, `ciel()` and `rint()`.

In [52]:
x = np.arange(0,2*np.pi+np.pi/2,np.pi/2)
print(np.sin(x))

[  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00
  -2.44929360e-16]


Apart from element-wise operations, there are some functions that give an output based on the entire array. These are fairly self-explanatory: `sum()`, `prod()`, `mean()`, `var()`, `std()`, `min()`, `max()`, `argmin()`, and `argmax()` (the latter two return the indices of min and max).

In [53]:
x = np.arange(10,21,2)
print(np.sum(x))

90


In [54]:
print(np.max(x))

20


In [55]:
print(np.argmax(x))

5


These functions also take an optional `axis` argument for multidimentional arrays.

In [56]:
x = np.array([[1,2,3],[4,5,6]])
print(np.prod(x,axis=0))

[ 4 10 18]


### Array iteration
Again, as we say with lists, we can iterate through the elements of an array.

In [57]:
x = np.array([1,2,3])
for item in x:
    print(item)

1
2
3


In [58]:
x = np.array([[1,2,3],[4,5,6]])
for item in x:
    print(item)

[1 2 3]
[4 5 6]


In [59]:
for a,b,c in x:
    print(a,b,c)

1 2 3
4 5 6


## Vectors and Matrices
Arrays can also be treated as vectors and matrices. Vector and matrix multiplication can be performed in a few ways, using the `dot()` function...

In [60]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.dot(x,y)) # x0*y0 + x1*y1 + x2*y2

32


..or using the `@` operator (not available in versions before 3.5)...

In [61]:
print(x@y)

32


In [62]:
x = np.array([1,2])
y = np.array([[3,4,5],[6,7,8]])
print(x@y)

[15 18 21]


...or defining the object as a matrix and using the `*` operator.

In [63]:
x = np.matrix([1,2,3])
y = np.matrix([4,5,6])
print(x*np.transpose(y))

[[32]]


There are additional functions for `inner()`, `outer()`, and `cross()` products. The inner product returns a scaler from two vectors $\mathbf{A} = [A_1, A_2,...]$ and $\mathbf{B} = [B_1, B_2,...]$ as $$\mathbf{A}\cdot \mathbf{B} = \mathbf{A^T} \mathbf{B} = \begin{bmatrix}A_1&A_2&A_3\end{bmatrix} \begin{bmatrix}B_1\\B_2\\B_3\end{bmatrix} = \sum_{i=1}^n A_i B_i$$ 

In [64]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.inner(x,y))

32


The outer product returns a matrix and is defined as $$ \mathbf{A} \otimes \mathbf{B} = \mathbf{A} \mathbf{B^T} = \begin{bmatrix}A_1\\A_2\\A_3\end{bmatrix} \begin{bmatrix}B_1&B_2&B_3\end{bmatrix} = \begin{bmatrix}A_1 B_1&A_1 B_2&A_1 B_3\\A_2 B_1&A_2 B_2&A_2 B_3\\A_3 B_1&A_3 B_2&A_3 B_3 \end{bmatrix}$$ 

In [65]:
print(np.outer(x,y)) # xyT

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


And the cross product is $$ \mathbf{A} \times \mathbf{B} = \begin{bmatrix} \begin{vmatrix} A_2&A_3\\B_2&B_3 \end{vmatrix} & -\begin{vmatrix} A_1&A_3\\B_1&B_3 \end{vmatrix} & \begin{vmatrix} A_1&A_2\\B_1&B_2 \end{vmatrix} \end{bmatrix} = \begin{bmatrix} A_2 B_3 - A_3 B_2 & -(A_1 B_3 - A_3 B_1) & A_1 B_2 - A_2 B_1\end{bmatrix}$$

In [66]:
print(np.cross(x,y))

[-3  6 -3]


And beyond this there is a whole linear algebra sub-module `linalg`, e.g.

In [67]:
x = np.array([[1,2],[3,4]])
print(np.linalg.det(x)) # x0*y1 - x1*y0

-2.0


## Further Reading
Although we've seen many of the key concepts needed for working with arrays in NumPy, there are still a large number of things it can do that we haven't have time to look at. If you think of something that sounds like it should be part of NumPy, it's probably available and you read how it works in the documentation, https://docs.scipy.org/doc/numpy/reference/. MATLAB users might also be interested in reading further about the differences and similarities it has with NumPy, https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html.